server:
  port: 8099
spring:
  application:
    name: easy-sys
  #main:
      #allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/easy?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
      username: fantasy
      password: fantasy
  thymeleaf:
       cache: false
       mode: HTML
# mybatis 配置
mybatis:
#  type-aliases-package: com.boot.shiro.entity   # 所有Entity别名类所在包
  mapper-locations: classpath:mapper/*.xml      # mapper映射文件
logging:
  level:
    root: info